# Generated by Django 4.0.2 on 2022-02-18 19:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Title must be greater than 2 characters')])),
                ('roll', models.CharField(default='', max_length=10)),
                ('email', models.CharField(default='', max_length=128)),
                ('password', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
